site_name: Shape Shifter Curse Wiki
nav:
    - Home: index.md
    - Versions:
        - Update Logs: update_log/update_log.md
    - Mod Content Guide: 
        - Brief Introduction: mod_content/brief_introduction.md
        - Mod Specific Items: mod_content/mod_specific_items.md
        - Enable Mod Content: mod_content/enable_mod_content.md
        - Transform Status Effect: mod_content/transform_status_effect.md
        - Form Types: mod_content/form_types.md
        - Form Ability Overview: mod_content/form_ability_overview.md
        - Form Change And Recovery: mod_content/form_change_and_recovery.md
        - Morphscale Armors: mod_content/morphscale_armors.md
        - Form Specific Tools And Trinkets: mod_content/form-specific_tools_and_trinkets.md
        - Mod Config: mod_content/mod_config.md
        - In Game Commands: mod_content/commands.md
        - FAQ: mod_content/common_issues.md
    - Creating Custom Forms:
        - Overview: custom_forms/overview.md
        - Resource Pack/Datapack Structure: custom_forms/pack_example.md
        - Configure Form Definition JSON: custom_forms/form_definition_json.md
        - Adding Custom Form Models and Animations: custom_forms/originfur_resource_pack.md
        - Adding Custom Form Powers: custom_forms/origins_data_pack.md
        - Adding Color Customization to Custom Forms: custom_forms/custom_form_colormask.md
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - autorefs
  - alias
  - categories
markdown_extensions:
    - toc:
        separator: "_"
    - admonition